# Playbook for Buffalo BHR-4GRV
- name: setup OpenWrt
  hosts: openwrt 
  become: True 
  vars:
    default_gw: 192.168.57.1
  tasks:
  - name: add route to default gw permanently 
#    command: route add default gw {{ default_gw }}
    command: "{{item}}"
    with_items:
      - uci set network.wan.gateway={{default_gw}}
      - uci commit
      - /etc/init.d/network reload
    failed_when: False
  - name: install packages 
    opkg: name={{item}} state=present update_cache=yes
    with_items:
      - python-pip
      - ip
      - tcpdump
      - openvswitch
      - coreutils-stty
      - kmod-usb-serial
      - kmod-usb-serial-ftdi
      - mosquitto
      - mosquitto-client
      - libmosquitto
#     - kmod-usb-ohci
#     - kmod-usbip
#     - kmod-usbip-server
#     - kmod-usbip-client
#     - usbip
#     - usbip-client
#     - http://downloads.openwrt.org/attitude_adjustment/12.09/ar71xx/generic/packages/usbip_1.1.1-2_ar71xx.ipk
#     - http://downloads.openwrt.org/attitude_adjustment/12.09/ar71xx/generic/packages/usbip-client_1.1.1-2_ar71xx.ipk
#     - http://downloads.openwrt.org/attitude_adjustment/12.09/ar71xx/generic/packages/usbip-server_1.1.1-2_ar71xx.ipk
      - udev
      - usbutils
